In [1]:
!pip install bing-image-downloader

In [2]:
!pip install ipython-autotime
%load_ext autotime

time: 200 µs (started: 2021-02-22 16:39:57 +00:00)


In [3]:
!mkdir images

time: 110 ms (started: 2021-02-22 16:40:27 +00:00)


In [4]:
from bing_image_downloader import downloader
downloader.download("fruits", limit=30,output_dir='images', adult_filter_off = True)



[!!]Indexing page: 1

[%] Indexed 30 Images on Page 1.


[%] Downloading Image #1 from https://media1.fdncms.com/inlander/imager/u/original/4871288/fruits_veggies.jpg_.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://blog.ediblearrangements.com/wp-content/uploads/2019/08/fruits-in-season.jpg
[%] File Downloaded !

[%] Downloading Image #3 from http://www.barbiemartini.com/wp-content/uploads/2014/07/Top-Fruits-Vegetables.jpg
[%] File Downloaded !

[%] Downloading Image #4 from http://attemptnwin.com/wp-content/uploads/2014/10/fruits2.jpg
[%] File Downloaded !

[%] Downloading Image #5 from http://www.fruitsinfo.com/fruit-facts/wp-content/uploads/2010/08/fruit.jpg
[Error]Invalid image, not saving http://www.fruitsinfo.com/fruit-facts/wp-content/uploads/2010/08/fruit.jpg

[!] Issue getting: http://www.fruitsinfo.com/fruit-facts/wp-content/uploads/2010/08/fruit.jpg
[!] Error:: No active exception to reraise
[%] Downloading Image #5 from https://policygenius-blog.imgix.net

In [5]:
from bing_image_downloader import downloader
downloader.download("chair", limit=30,output_dir='images', adult_filter_off = True)



[!!]Indexing page: 1

[%] Indexed 30 Images on Page 1.


[%] Downloading Image #1 from http://www.antiquepurveyor.com/productimages/wheatsheaf-carved-shield-back-arm-chair-8195.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://assets3.parliament.uk/iv/original/ImageVault/Images/scope_0/filename_2oti5DZCW81C8JbBASpQ.jpg/storage_Edited/ImageVaultHandler.aspx.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://www.modernmiami.com/media/catalog/product/cache/3/thumbnail/9df78eab33525d08d6e5fb8d27136e95/m/a/maxi-black-oak-chair---dsc_1414.jpg
[!] Issue getting: https://www.modernmiami.com/media/catalog/product/cache/3/thumbnail/9df78eab33525d08d6e5fb8d27136e95/m/a/maxi-black-oak-chair---dsc_1414.jpg
[!] Error:: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>
[%] Downloading Image #3 from http://grshop.com/media/catalog/product/cache/1/image/1800x/040ec09b1e35df139433887a97daa66f/e/a/eames_molded_side_chair-3.jpg
[%] File 

In [6]:
from bing_image_downloader import downloader
downloader.download("dog", limit=30,output_dir='images', adult_filter_off = True)



[!!]Indexing page: 1

[%] Indexed 30 Images on Page 1.


[%] Downloading Image #1 from https://peopledotcom.files.wordpress.com/2017/05/downward-dog-2.jpg
[!] Issue getting: https://peopledotcom.files.wordpress.com/2017/05/downward-dog-2.jpg
[!] Error:: HTTP Error 403: Forbidden
[%] Downloading Image #1 from http://www.bkcphoto.com/Portraits/wp-content/uploads/2014/03/Dog_Faces_06.jpg
[!] Issue getting: http://www.bkcphoto.com/Portraits/wp-content/uploads/2014/03/Dog_Faces_06.jpg
[!] Error:: HTTP Error 404: Not Found
[%] Downloading Image #1 from https://sydneydruglawyers.com.au/wp-content/uploads/sniffer-dog-1024x1024.jpg
[%] File Downloaded !

[%] Downloading Image #2 from http://www.parade.pet/assets-v2/images/dog/img-dogs/02.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://www.sciencealert.com/images/articles/processed/dog-doubt_1024.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://pawsh-magazine.com/wp-content/uploads/2019/02/online-dog-magazine-n

In [7]:
#Preprocessing the images

import os
import matplotlib.pyplot as plt
import numpy as np
from skimage.io import imread
from skimage.transform import resize

time: 1.02 s (started: 2021-02-22 16:42:56 +00:00)


In [11]:
# Flattening the images
Target = []
Images = []
Flattened_data = []
DATADIR = '/content/images'
CATAGORIES = ['chair', 'dog', 'fruits']


time: 3.25 ms (started: 2021-02-22 16:49:15 +00:00)


In [12]:
for catagory in CATAGORIES :
  class_num = CATAGORIES.index(catagory)
  path = os.path.join(DATADIR,catagory)
  # Now we will read the values by iterating and is stored
  for img in os.listdir(path) :
    Image_Array = imread(os.path.join(path,img))
    # plt.imshow(Image_Array) to show the images
    Image_Resized = resize(Image_Array,(150,150,3))
    # Now passing the flattened verion
    Flattened_data.append(Image_Resized.flatten())
    Images.append(Image_Resized)
    Target.append(class_num)



time: 1min 28s (started: 2021-02-22 16:49:21 +00:00)


In [13]:
Flattened_data = np.array(Flattened_data)
Images = np.array(Images)
Target = np.array(Target)

time: 64.2 ms (started: 2021-02-22 16:51:10 +00:00)


In [14]:
Flattened_data.shape

(90, 67500)

time: 4.81 ms (started: 2021-02-22 16:51:12 +00:00)


In [15]:
Target.shape

(90,)

time: 3.34 ms (started: 2021-02-22 16:51:14 +00:00)


In [16]:
np.unique(Target, return_counts=True)

(array([0, 1, 2]), array([30, 30, 30]))

time: 4.16 ms (started: 2021-02-22 16:51:19 +00:00)


In [17]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm

time: 326 ms (started: 2021-02-22 16:51:21 +00:00)


In [18]:
# Spliting Data into Training and Testing
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(Flattened_data, Target, test_size = 0.3, random_state = 109)

time: 18.3 ms (started: 2021-02-22 16:51:24 +00:00)


In [19]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm
param_grid = [
  {'C': [1, 10, 100, 1000], 'kernel': ['linear']},
  {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel': ['rbf']},
 ]
svc = svm.SVC(probability = True)
clf = GridSearchCV(svc,param_grid)
clf.fit(x_train,y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=True, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

time: 2min 1s (started: 2021-02-22 16:51:30 +00:00)


In [20]:
y_pred = clf.predict(x_test)
y_pred

array([1, 1, 2, 2, 2, 0, 0, 1, 0, 0, 1, 0, 1, 2, 2, 1, 2, 0, 0, 1, 2, 0,
       2, 0, 2, 2, 1])

time: 189 ms (started: 2021-02-22 16:54:00 +00:00)


In [21]:
y_test

array([1, 0, 1, 2, 2, 1, 0, 1, 1, 0, 1, 0, 1, 2, 2, 1, 2, 1, 0, 1, 2, 2,
       2, 0, 0, 0, 1])

time: 8.95 ms (started: 2021-02-22 16:54:06 +00:00)


In [22]:
from sklearn.metrics import accuracy_score, confusion_matrix

time: 1.1 ms (started: 2021-02-22 16:54:08 +00:00)


In [23]:
accuracy_score(y_pred, y_test)

0.7037037037037037

time: 3.59 ms (started: 2021-02-22 16:54:11 +00:00)


In [24]:
confusion_matrix(y_pred, y_test)

array([[5, 3, 1],
       [1, 7, 0],
       [2, 1, 7]])

time: 4.18 ms (started: 2021-02-22 16:54:13 +00:00)


In [25]:
# Save the model using Pickel library
import pickle
pickle.dump(clf, open('img_model.p', 'wb' ))

time: 45.2 ms (started: 2021-02-22 16:54:15 +00:00)


In [35]:
model = pickle.load(open('img_model.p', 'rb'))

time: 26.4 ms (started: 2021-02-22 17:45:16 +00:00)


In [36]:
# Testing a brand new image
Flattened_data = []
url = input("Enter URL of the image")
img = imread(url)
img_resized = resize(img,(150,150,3))
Flattened_data.append(img_resized.flatten())
Flattened_data = np.array(Flattened_data)
y_out = model.predict(Flattened_data)
y_out = CATAGORIES[y_out[0]]
print("Predicted Output :")
print(y_out)

Enter URL of the imagehttps://th.bing.com/th/id/R210443c33abce84e4d9b2a7f9ab00c8c?rik=I%2b2Dw%2bdNhP6Dpg&riu=http%3a%2f%2fnewmanwray.co.uk%2fwp-content%2fgallery%2fpet_portrait_2015_2_pt1%2fdog_photo_portrait_002.jpg&ehk=PCw0VGtrkEd5soonCfUBYqmi0pIzl19ySe3dJmvp3Ds%3d&risl=&pid=ImgRaw
Predicted Output :
dog
time: 2min 9s (started: 2021-02-22 17:45:20 +00:00)


In [ ]:
#!pip install streamlit
#!pip install pyngrok
#from pyngrok import ngrok

     |████████████████████████████████| 7.5MB 10.6MB/s 
     |████████████████████████████████| 81kB 6.4MB/s 
     |████████████████████████████████| 112kB 43.8MB/s 
     |████████████████████████████████| 4.6MB 45.8MB/s 
     |████████████████████████████████| 163kB 52.0MB/s 
     |████████████████████████████████| 122kB 36.7MB/s 
     |████████████████████████████████| 71kB 5.8MB/s 
  Created wheel for blinker: filename=blinker-1.4-cp36-none-any.whl size=13450 sha256=f9094cccf02ec00b0c0752168c669559ac02dbba9d94572085b8cdd908215cec
  Stored in directory: /root/.cache/pip/wheels/92/a0/00/8690a57883956a301d91cf4ec999cc0b258b01e3f548f86e89
Successfully built blinker
ERROR: google-colab 1.0.0 has requirement ipykernel~=4.10, but you'll have ipykernel 5.5.0 which is incompatible.
  Found existing installation: ipykernel 4.10.1
    Uninstalling ipykernel-4.10.1:
      Successfully uninstalled ipykernel-4.10.1


     |████████████████████████████████| 737kB 12.6MB/s 
  Created wheel for pyngrok: filename=pyngrok-5.0.2-cp36-none-any.whl size=18972 sha256=3f19d83839f7ad287ad2f48a929aa3408a474c6bbfe5245da900d2e6bf441a9c
  Stored in directory: /root/.cache/pip/wheels/e1/94/52/c88ac157149e3506d377ae531697455b43ab49b76d3f2cc862
Successfully built pyngrok


In [ ]:
# Deployment:
# 1. Web Page
# 2. Web App
# 3. Mobile App

In [ ]:
#%%writefile app.py
#import streamlit as st
#Preprocessing the images

#import os
#import matplotlib.pyplot as plt
#import numpy as np
#from skimage.io import imread
#from skimage.transform import resize
#import pickle
#from PIL import Image
#st.title('Image Classifier')
#st.text('Upload the image')

#model = pickle.load(open('img_model.p', 'rb'))
#uploaded_file = st.file_uploader("Choose an image...", type="jpg")
#if uploaded_file is not None:
  #img = Image.open(uploaded_file)
  #st.image(img, caption='Uploaded Image')

In [ ]:
#!nohup streamlit run app.py &
#url = ngrok.connect(port = '8501')
#url